### ISSUE TITLE
Nom des appareils et entités

### ISSUE THREAD

**Issue by malendure81** [droso-hass/idfm#1]
L'intégration fonctionne bien mais il faut renommer les appareils ainsi que les entités pour s'y retrouver sinon elles ont toujours les mêmes noms.
Est il possible de l'intégrer ? Merci

**Comment by drosoCode** [comment]
Cela devrait etre mieux avec la v1.1, pourriez-vous tester ?
(Attention il faudra supprimer la configuration existante et la re-créer)

**Comment by malendure81** [comment]
Installé.
C'est parfait.

Petit souci quand on choisi le RERB : aucune direction n'est disponible.

**Comment by drosoCode** [comment]
J'ai testé à l'instant, en partant de Chatelet on a bien toutes les directions (Aeroport CDG, Massy Palaiseau, Mitry-Claye, Robinson, Saint Remy les Chevreuse), cela est peut etre du au moment ou vous avez fait la configuration (l'api ne permettant pas de récupérer la liste des directions, celle ci est déterminée a partir des directions des prochains trains, il est donc possible qu'il en manque si aucun des prochains trains ne va vers cette direction).
Dans tous les cas, la direction du train arrivant devrait etre renseignée dans l'attribut `direction` de chaque entity.

**Comment by malendure81** [comment]
OK J'ai testé avec la gare de Villepinte

**Comment by Gonioul** [comment]
Il faudrait rajouter la ligne dans le nom des entités, en effet il y a plusieurs cas qui peut poser problème, comme Houilles-Carrière, Conflans-Fin-d'Oise et Asnières-sur-Seine direction terminus Paris-Saint Lazare peuvent se faire par le transilien L ou J.
Garder idfm en premier permet aussi de les filtrer dans EntityChecker (sensor.idfm*), sinon la nuit les sensors sont détectés comme non disponibles et remontent des alarmes.

**Comment by drosoCode** [comment]
@[malendure81](https://github.com/malendure81)
Effectivement, apres verification aucune direction n'est indiquée pour cette gare de départ, mais le problème semble etre du coté d'ile de france mobilités car que ce soit sur leur [site](https://me-deplacer.iledefrance-mobilites.fr/fiches-horaires/train/line%3AIDFM%3AC01743/horaires?arrivalId=stop_area%3AIDFM%3A474151&date=2022-04-14T20%3A15&departureId=stop_area%3AIDFM%3A73547) ou sur l'[API](https://api-iv.iledefrance-mobilites.fr/lines/line:IDFM:C01743/stops/stop_area:IDFM:73547/realTime), les informations temps-réel sont indisponibles.

**Comment by drosoCode** [comment]
@[Gonioul](https://github.com/Gonioul)
Effectivement je n'avais pas pensé a ces cas de figures, je pense plutot ajouter le nom de la ligne dans le nom du device associé, le nom des entities etant déja très long.

Concernant les problèmes la nuit, c'est totalement normal, les sensors sont indiqués comme indisponibles car l'API temps réel ne remonte aucun prochain train (puisqu'il n'y en a pas avant le matin) et le sensor de statut (qui remonte les infos trafic) peut remonter des alarmes en fonction de la ligne suivie (par exemple la ligne 4 du metro a une info trafic concernant sa fermeture la nuit jusqu'en juin)

**Comment by Gonioul** [comment]
Oui je disais juste que garder un préfixe typique de l'intégration permettrait de gérer les entités autrement, soit en ignorant les indisponibilités, soit en augmentant le délai.

**Comment by drosoCode** [comment]
Ah oui, j'avais mal compris.
J'ajouterai ces 2 modifs dans la prochaine release.
