### ISSUE TITLE
Next scheduled stops are in the past

### ISSUE THREAD

**Issue by Egglestron** [droso-hass/idfm#10]
![image](https://user-images.githubusercontent.com/15892040/199300104-acd248fb-03d0-4323-b123-d137f18e2fc9.png)

As shown in this screenshot, some stops seem to provide information of past schedules (which can be useful to check for missed trains), but in some cases, it also means that all 4 provided entities are filled with past schedules information.

It would be nice to deal with that case in some way: create separate entities for past schedules, or add a configuration filter to show only schedules that are within a fixed number of minutes past current time (based on the difference between `ExpectedDepartureTime` and `ResponseTimestamp` JSON attributes).

Thank you for your work! I hope this could be added in a future release!

**Comment by drosoCode** [comment]
Hi,

Thanks for reporting this issue, I didn't know that the API could return schedules in the past.

I saw your PR and will get it merged this week.

As the "past schedules" are more of a bug than a feature, I think that we can just omit them (as the goal of this integration is more to provide the next schedules).

**Comment by drosoCode** [comment]
I have merged your PR, the bug should now be fixed in v2.0.2

I also merged the one on idfm-api, and I am working on adding the new attributes to this integration.
