### ISSUE TITLE
Pas de filtrage sur la ligne sélectionnée ?

### ISSUE THREAD

**Issue by rhoudinet** [droso-hass/idfm#15]
J'habite Carrières sur Seine, et naturellement j'ai voulu configurer des lignes de transport qui me concernent, cependant les horaires des prochains passages obtenus me semblent erronés et ne pas correspondre ni à la réalité, ni à ce que peut m'indiquer l'app Ile de France Mobilité par exemple. J'ai tenté d'identifier pourquoi.
 
Je me suis penché plus particulièrement sur les horaires des prochains passage de bus, soit :

- ligne de bus 'A' (Keolis Argenteuil Boucles de Seine), à l'arrêt 'Égalité' en direction de la Gare de Houilles Carrières sur Seine
- ligne de bus 'L' (Keolis Argenteuil Boucles de Seine), à l'arrêt 'Égalité' en direction de la Gare de Houilles Carrières sur Seine

Donc, deux lignes de bus qui passent au même arrêt vers la même destination.

J'ai fouillé rapidement le code et je comprends que l'API via idfm_api retourne toutes les données d'un arrêt vers une destination ou direction donnée, sans discriminer quelle ligne est concernée. Je pense - sans certitude - que la raison pour laquelle les horaires me semblent erronés et que, dans mon cas, que je configure la ligne de bus 'A', ou la ligne de bus 'L' j'obtiens des horaires mélangés des deux lignes, puisque même arrêt et même destination.

A savoir que ce cas se représente aussi à la Gare de Houilles / Carrières sur Seine à destination de Paris, car y passent :
- Le train J vers Saint Lazare
- Le train L vers Saint Lazare

Donc ici aussi, même arrêt, même destination.

En sus, passe à la Gare de Houilles Carrières sur Seine, le RER A. Lorsque je veux configurer cette ligne depuis cette gare, le configurateur me propose entre autres destination et direction : 'Gare Saint Lazare' (où le RER A ne va pas) et de manière encore plus étonnante 'Caen'. Je présume que là aussi il y a mélange entre les lignes. Pour Caen, c'est peut être explicable par le fait que les trains de la ligne Paris – Caen - Cherbourg passent par la gare de Houilles Carrières sur Seine (sans s'y arrêter), enfin je crois.

**Comment by drosoCode** [comment]
Bonjour,
Je viens seulement de voir votre issue, effectivement les données ne sont pour l'instant filtrées que par arrêt et destination.

Votre supposition me semble donc etre la bonne et il devrait etre possible de rajouter un filtrage sur la ligne comme vous le suggérez (cette option n’était pas encore disponible lors de la création de ce package).

Il s'agit du même problème pour les directions, comme aucun filtrage sur la ligne n'est effectué, toutes les directions possibles depuis l'arret sélectionné sont proposées (indifféremment de la ligne sélectionnée).

Je n'ai pour l'instant pas assez de temps pour m'occuper de ce problème, mais je vous tiendrais informé lorsqu'il sera réglé.

**Comment by drosoCode** [comment]
Le problème devrait etre résolu dans la version 2.1.2
