### ISSUE TITLE
Problème à la selection de la ligne RER D

### ISSUE THREAD

**Issue by Soicnarf** [droso-hass/idfm#17]
Bonjour et merci de votre travail !
Je me trouve confronté à un problème dans l'assistant de configuration en choisissant Train puis D, j'ai une "Unknown error occurred"
Comme il n'y a pas de sélection de ligne j'ai pu choisir RER A et départ Gare de Lyon -> Arrivée Melun, mais je ne peux pas choisir la gare de mon domicile puis la destination Paris puisqu'il n'y a que la D qui passe par chez moi.

Petites questions subsidiaires: cette intégration n'affiche que les prochains heures de départs vers la destination n'est ce pas ? il n'y a pas d'attribut comme le nom de la mission ou l'horaire de départ que je n'aurai pas trouvé comment configurer dans  HA ?

Merci par avance de votre aide !
++
F.
p.s.: j'avais développé un script php pour intégration dans la solution Eedomus et j'étais passé par 
https://prim.iledefrance-mobilites.fr/marketplace/stop-monitoring?MonitoringRef=".STIF:StopPoint:Q:412815."&LineRef=".STIF:Line::C01728"
de façon à avoir la station de départ, ici Chatelet et la ligne, ici RER D, je filtrai ensuite en fonction de la mission qui m'intéressait ex: ZICO ou ZACO pour sortir les résultat vers le sud/Melun ou FACA pour les destinations nord/Goussainville.
(code à dispo si ça peut aider)

**Comment by Soicnarf** [comment]
même problème en choisissant Bus -> D/SNCF, il semble y avoir du dépassement de buffer 
(mais je me demande si ce n'est pas un bug dans l'API elle même sur le choix de la ligne D)
[...]
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 367, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/idfm/config_flow.py", line 91, in async_step_line
    return await self.async_step_stop()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/idfm/config_flow.py", line 130, in async_step_stop
    default=user_input.get(CONF_STOP) or names[0],
                                         ~~~~~^^^
IndexError: list index out of range

**Comment by drosoCode** [comment]
Le problème de sélection devrait etre résolu dans la version 2.1.2 (cela était du a un bug lors de l'export des arrets).

Pour les données renvoyées, on a pour chaque capteur la prochaine heure de départ et, en attributs, la destination, la direction, le statut du train (a quais ou non), le numero de quais et la ponctualité du train. J'ai aussi rajouté dans cette release l'attribut details, ou on peut trouver le nom de la mission pour les RER.

ps: j'utilise exactement la meme api :)

**Comment by Soicnarf** [comment]
Merci de ta réactivité c'est top !
Je viens de tester avec la version 2.1.2, donc possible de choisir la D mais après je cherche ma station mais ne la trouve pas, je vois bien celles autour (Boussy, Brunoy, Yerres...) mais pas de Combs-la-ville/Quincy
référence de ma station STIF:StopArea:SP:41366:

(super pour l'ajout des détails, la mission c'est bien utile !)

**Comment by drosoCode** [comment]
Effectivement, il y avait certains arrets manquants, cela devrait etre bon avec la 2.1.3

**Comment by jefforion** [comment]
Bonjour,
Je viens d'installer et j'ai de nouveau l'erreur "Unknown error occurred" quand je dois sélectionner si c'est BUS / Métro ...
Et il y a un redémarrage de HA qui ce lance au même moment.
Info des log après redémarrage :
```
Logger: homeassistant
Source: runner.py:145
First occurred: 00:01:02 (1 occurrences)
Last logged: 00:01:02

Error doing job: Unclosed client session
```

J'ai tester à différent moment de la journée, dans le doute. Tester avec une autre API Key aussi.

Avez-vous des idées ?
