### ISSUE TITLE
Le binary sensor est toujours OK, qu'il y ait des problèmes ou non

### ISSUE THREAD

**Issue by kalon33** [droso-hass/idfm#18]
Sur mes tableaux de bord qui comprennent la ligne RER C, les bus RATP 199, DM 151, CEAT 108... les capteurs info trafic remontent toujours OK quoi qu'il arrive, et pourtant en ce moment ce n'est pas l'occasion qui manque d'afficher autre chose.

Est-ce moi qui l'utilise mal ? Ou un souci quelque part ? J'ai par contre correctement mes temps d'attente pour ces lignes.

Merci d'avance pour l'aide !

**Comment by drosoCode** [comment]
Le temps d'attente et les messages d'info trafic utilisent des API différentes.
J'ai testé directement avec l'api pour le RER C et aucun message d'info n'est retourné (alors qu'ils sont bien présents sur le site d'idfm). 
Il semble donc que c'est un problème venant directement de l'API.
J'ai contacté les développeurs pour plus d'informations.

**Comment by kalon33** [comment]
Merci pour votre réponse. N'est-ce pas possible d'utiliser l'autre API d'info trafic pour remonter les messages, au moins ponctuellement ? C'est celle qui s'appelle ["general-message"](https://prim.iledefrance-mobilites.fr/fr/donnees-dynamiques/idfm-ivtr-info_trafic). C'est l'API [/coverage/fr-idf/{uri}/line_reports](https://prim.iledefrance-mobilites.fr/fr/donnees-dynamiques/idfm-navitia-line_reports) qui est actuellement utilisée ?

**Comment by drosoCode** [comment]
Effectivement, j'ai au final changé d'api. J'utilisais la [general-message](https://prim.iledefrance-mobilites.fr/fr/donnees-dynamiques/idfm-ivtr-info_trafic), je l'ai donc remplacée par l'API [/coverage/fr-idf/{uri}/line_reports](https://prim.iledefrance-mobilites.fr/fr/donnees-dynamiques/idfm-navitia-line_reports), qui couvre plus de services (confirmé par les développeurs).
Les messages devraient maintenant apparaitre avec la nouvelle version (v2.2.0) de l'integration.
