### ISSUE TITLE
Name of bus stop to be sorted in the same way as line

### ISSUE THREAD

**Issue by jugla** [droso-hass/idfm#2]
Thanks a lot for this custom integration.

I encounter this issue when I select a bus line: I get a lot bus stops with the same name . Indeed on RATP line 192, I have several times "mairie" (town hall).
Please can you add the liaibility to sort bus stop in the same way as you see them on the bus line map ==> thus the right "mairie" (town hall) can be selected.
Currently, it is sorted in alphabetic way.

NB : I have installed V1.1.0

**Comment by drosoCode** [comment]
Unfortunately the data returned by the API is unordered, so I have no way of sorting bus stops the same way as they are on the map, but I have added the city name to the stop name (in the version 1.1.1), so now you should get something like "Mairie - Sceaux" insead of just Mairie.

**Comment by jugla** [comment]
great, I will try !

**Comment by jugla** [comment]
Hello,
It's great to have added to the town name. For me it's ok.
