### ISSUE TITLE
Attribute of sensor on Mushroom Entity Card

### ISSUE THREAD

**Issue by momomie** [droso-hass/idfm#21]
Hi, 

First thx for this integration ! 

I have a problem and after several research i can't fix it. 

How to use feature attributes in a Mushroom map?

I mean, display "Destination" attribute as title
But above all display the "Description" attribute when there is a problem on the line instead of simply displaying "Problem"

Thanks for your help !
![brave_00Jf4ugQfe](https://github.com/droso-hass/idfm/assets/6598997/d202251c-f031-4ff9-ac67-67fd58be03dd)

**Comment by drosoCode** [comment]
Hi,
I'm not familiar with mushroom cards, you should probably ask this on the [community forums](https://community.home-assistant.io/c/configuration/frontend/33).
