### ISSUE TITLE
Unknown error occured during transport type selection 

### ISSUE THREAD

**Issue by Lhemamou** [droso-hass/idfm#22]
Hi :)

thanks for the HA integration. I am trying to install it but after entering my API key and select my transport type, nothing happens, only a error message (see attached).

Any idea to solve that ?

Thanks
![Capture d'écran 2023-12-31 141511](https://github.com/droso-hass/idfm/assets/17457873/776a321f-513b-4628-815f-c86e27dd9271)

**Comment by JiDW** [comment]
You can check the logs (from the integration page, enable debbuging, try it, then stop debugging)

Last time I got this error was because I failed to properly copy my API key.
