### ISSUE TITLE
Invalid timestamp on iOS

### ISSUE THREAD

**Issue by Egglestron** [droso-hass/idfm#23]
Hi and happy new year!

The timestamps returned by the integration do not comply with the isoformat expected by iOS devices:

![Invalid timestamp screenshot](https://github.com/droso-hass/idfm/assets/15892040/e633d331-9f27-4c98-872b-173b9f3cafd7)

The sensor value should have a 'T' instead of a whitespace.
Example of incorrect sensor value:
<img width="184" alt="image" src="https://github.com/droso-hass/idfm/assets/15892040/76efe437-f578-4ce5-9c9d-ddac62d99951">

The issue is known. Reference to the global issue and solution:
https://github.com/home-assistant/frontend/issues/8072

**Comment by drosoCode** [comment]
Hi,
I'm afraid that this is out of my control as the integration directly returns a python datetime object (see [sensors.py](https://github.com/droso-hass/idfm/blob/main/custom_components/idfm/sensor.py#L80)) and doesn't handle the formatting of these objects. You should probably open an issue on the core/frontend repo of home assistant is the problem persists.
