### ISSUE TITLE
Documentation / Screenshot 🙏

### ISSUE THREAD

**Issue by dathosim** [droso-hass/idfm#5]
Il manque de la documentation sur cette intégration 
Je l'ai installé via HACS 
J'ai ensuite installé l'intégration 
Le flow me demande un type, une ligne, un arrêt : parfait 
Mais...
A la fin, le sensor est soit vide, soit contient une description du problème sur la ligne ?!?
Mais pas les horaires de passage à la station 🧐
Ai-je raté quelque chose ?

**Comment by jugla** [comment]
Hello
Could be linked to #4 ?

**Comment by drosoCode** [comment]
Cela peut etre du a un bug des précédentes version, pourriez-vous tester avec la dernière disponible (1.1.3) ?

Normalement, vous devriez obtenir 1 device avec 4 entities associées (comme sur les photos ci-dessous): 
 - 1 sensor qui indique les éventuels problèmes de la ligne
 - 3 sensors qui indiquent les 3 prochains horaires de passage
![screen_1](https://user-images.githubusercontent.com/44530920/163715309-c8d7cdc3-e213-4fa2-9c14-40b28c2e240b.png)
![screen_2](https://user-images.githubusercontent.com/44530920/163715311-5188477a-3ed3-4e4c-908b-45c550402a80.png)

**Comment by dathosim** [comment]
@drosoCode : j'ai installé la dernière version (et la dernière version de HA)
J'ai bien 4 sensor par installation
Par contre, les heures de passage me renvoie des "invalid timestamp"
<img width="429" alt="Capture d’écran 2022-04-24 à 20 18 24" src="https://user-images.githubusercontent.com/47037724/164990817-9b92a9cf-3ace-4869-8f19-09d899931723.png">
<img width="429" alt="Capture d’écran 2022-04-24 à 20 18 24" src="https://user-images.githubusercontent.com/47037724/164990821-6b496a2c-8bb8-402b-a0cb-34164ed63e6a.png">

**Comment by drosoCode** [comment]
j'ai essayé avec les memes parametres que les votes et cela fonctionne de mon coté (HA 2022.4, IDFM 1.1.4).
Pouvez vous regarder s'il y a des erreurs dans vos logs ?

**Comment by dathosim** [comment]
```
2022-04-26 14:08:50 ERROR (MainThread) [idfm_api] Timeout error fetching information from https://api-iv.iledefrance-mobilites.fr/lines/line:IDFM:C01127/stops/stop_area:IDFM:73665/realTime -
2022-04-26 14:08:50 ERROR (MainThread) [custom_components.idfm] Error fetching idfm data:
2022-04-26 14:09:51 INFO (MainThread) [custom_components.idfm] Fetching idfm data recovered

```

**Comment by drosoCode** [comment]
Une nouvelle version majeure de l'intégration est disponible (v2.0.0), elle a donc connu de nombreuses modifications, pourriez-vous re-tester avec celle-ci ?

**Comment by jugla** [comment]
Hello,
Ca marche bien sur les bus.
Par contre sur le terminus de la ligne B RER Robinson, je n'arrive pas à mettre la bonne option pour que le senseur soit tjrs dispo ...

**Comment by jugla** [comment]
Some logs:
```
2022-10-01 22:50:41.878 WARNING (MainThread) [homeassistant.config_entries] Config entry 'B - Robinson - Sceaux' for idfm integration not ready yet: None; Retrying in background
```
...
```
2022-10-01 22:51:09.500 ERROR (MainThread) [custom_components.idfm] Error fetching idfm data:
```

There is no details after `ERROR`

**Comment by jugla** [comment]
Pour mon senseur "RER B - terminus Robinson" voila la tete qu'il a ...
Trait rouge : dispo
Trait Gris : indisponible 

![image](https://user-images.githubusercontent.com/59493499/193430957-6b51a57b-a6fc-40f0-9271-fd9f7892a062.png)

**Comment by drosoCode** [comment]
Hello,
Ca devrais etre corrigé dans la v2.0.1
