### ISSUE TITLE
Too many sensors got the same name

### ISSUE THREAD

**Issue by jugla** [droso-hass/idfm#7]
Let's say you have a train station with bus line from there.
If you choose any direction for the train or bus all sensors got the same name. Indeed the template name is : 
idfm_station_any. (any is the direction)
Please can you add line name (as you have done in binary sensor) ?
Or something that's allow to distinguish sensor ?
Thanks in advance

**Comment by drosoCode** [comment]
I've thought of adding it too, but the generated title is already really long, so as the probablilty of having both the same departure and direction for two lines is pretty low, I decided to not add it in the entity name.

However you can still differenciate the different lines by looking at the entity's device (which does have the line name in the title) and rename the entities.

**Comment by jugla** [comment]
Great, I will try the rename :-)
