### ISSUE TITLE
Limitation d'accès à l'API

### ISSUE THREAD

**Issue by mdeweerd** [droso-hass/idfm#9]
J'ai l'erreur suivante en se moment:
```plaintext
2022-06-01 16:50:54 ERROR (MainThread) [idfm_api] Error while fetching information from https://api-iv.iledefrance-mobilites.fr/lines/line:IDFM:xxx/stops/stop_area:IDFM:xxxx/realTime - None
2022-06-01 16:51:15 ERROR (MainThread) [idfm_api] Timeout error fetching information from https://api-iv.iledefrance-mobilites.fr/lines/line:IDFM:xxxx/stops/stop_area:IDFM:xxxx/realTime -
```
 et le retour JSON dit:

```json
{"nextDepartures":{"data":[],"statusCode":503,"errorMessage":"REALTIME_SERVICE_ERROR"},"crowdsourcingReports":{"congestions":[],"statusCode":503,"errorMessage":"Crowdsourcing Service is unavailable"}}
```

J'en conclus qu'il y a une limitation du nombre d'appels.

Je vais me limiter à https://github.com/lesensei/idfm-card qui réalise les demandes seulement lorsque c'est affiché.

**Comment by mdeweerd** [comment]
Ok, je vois l'utilité pour les automatismes.

A ce moment là il faut peut-être prévoir de pouvoir dépendre d'un état/condition pour mettre à jour ou non les données et de limiter ainsi le nombre d'appels dans la journée. (c'est peut-être déjà le cas, mais je n'ai pas vérifié).

**Comment by ltoinel** [comment]
Cette API est une API interne au portail Web IDFM.
Les API officiellement autorisée aux développeurs tiers sont celles du portail B2B d'IDFM : 
https://prim.iledefrance-mobilites.fr/fr/donnees-dynamiques/idfm-ivtr-requete_unitaire?type=k&apiId=idfm-ivtr-requete_unitaire

**Comment by drosoCode** [comment]
Effectivement, la migration vers cette API est d'ailleurs bien prévue, pour peu que j'ai le temps de me pencher dessus.
J'aurai d'ailleurs quelques questions concernant cette nouvelle api:

En regardant rapidement la documentation j'ai pu voir qu'elle nécessitait un token d'auth (contrairement a celle actuellement utilisée), existe-t-il un moyen simple pour qu'un utilisateur puisse recuperer un tel token ? (ne serait-il pas plus simple s'il pouvait directement se connecter avec son compte IDFM existant au lieu de devoir en créer un spécifiquement pour PRIM ?)

J'ai également pu trouver la liste des [zones d'arrets](https://data.iledefrance-mobilites.fr/explore/dataset/zones-d-arrets/information/) et des [lignes](https://data.iledefrance-mobilites.fr/explore/dataset/referentiel-des-lignes/information) du réseau, mais existe-t-il un document permettant de faire le lien entre ces 2 entitées (ZdAId <-> ID_Line) afin de connaitre les zones d'arrets disponibles pour une certaine ligne ?

**Comment by ltoinel** [comment]
Bonjour @drosoCode,

Pour le token, il est récupérable sur cette page du portail PRIM : https://prim.iledefrance-mobilites.fr/fr/mon-jeton-api

Pour le mapping arrêt / ligne, tu as ce fichier:
https://prim.iledefrance-mobilites.fr/fr/donnees-statiques/arrets-lignes?staticDataSlug=arrets-lignes

Il faudrait trouver un mécanisme plus intelligent que de requêter en permanence les API d'horaires. 
Aujourd'hui, le plugin tel qu'il est utilisé génère des centaines de milliers d'appels et la quasi totalité des données récupérées ne sont pas utilisées.  Ce n'est pas super green. Il faudrait l'activer seulement sur un horaire de départ.

**Comment by drosoCode** [comment]
Merci pour ces informations, je m'occupe de la mise a jour des que possible.

**Comment by drosoCode** [comment]
Bonjour @ltoinel,

Bonne nouvelle, la nouvelle version de l'integration est enfin prete.
Les APIs du portail PRIM ont donc remplacé les APIs internes.
Concernant les mises a jour, l'interval a été changé par défaut a 3min et désactivé lorsqu'il n'y a pas de passages.
Il est aussi possible de désactiver les mises a jour automatiques pour le faire manuellement (tout est expliqué dans le readme).
